version: '3.8'

services:
  nextjs-app:
    image: ahmedhassan711/nextjs-app:latest
    container_name: nextjs-app-container
    build:
      context: .
      target: runner
    restart: always
    environment:
      - NODE_ENV=production
    expose:
      - 3000

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    depends_on:
      - nextjs-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro   # ✅ will hold SSL certs
    restart: always
