name: tsc

on: [push, pull_request]

jobs:
  tsc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node (with cache)
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: tsc
        run: pnpm tsc --noEmit --pretty false
